version: 2

builds:
  # macOS build (native)
  - id: "mymy-macos"
    builder: rust
    binary: my
    targets:
      - aarch64-apple-darwin # Native target for Apple Silicon
    dir: "."
    tool: "cargo"
    command: build
    flags:
      - --release

  # Linux build (cross-compiled from macOS)
  - id: "mymy-linux"
    builder: rust
    binary: my
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
    dir: "."
    command: zigbuild
    flags:
      - --release
    env:
      - CARGO_NET_GIT_FETCH_WITH_CLI=true

# Configuration for archives
archives:
  - id: mymy-archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: darwin
        formats: ["zip"]
      - goos: linux
        formats: ["tar.gz"]
    files:
      - LICENSE
      - README.md

# Linux package configuration (DEB)
nfpms:
  - id: mymy-packages
    package_name: mymy
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Arch }}"

    vendor: Théo Crevon
    homepage: https://github.com/oleiade/mymy
    maintainer: Théo Crevon <theo@crevon.me>
    description: Access the most common information about your system using a single command
    license: MIT

    section: utils
    priority: optional

    contents:
      - src: LICENSE
        dst: /usr/share/doc/mymy/LICENSE
      - src: README.md
        dst: /usr/share/doc/mymy/README.md

    formats:
      - apk
      - deb
      - rpm
      - archlinux

# Homebrew tap configuration
brews:
  - name: mymy
    repository:
      owner: oleiade
      name: homebrew-tap
      token: "{{ .Env.DEPLOYMENT_ACCESS_TOKEN }}"
    directory: Formula
    homepage: https://github.com/oleiade/mymy
    description: Access the most common information about your system using a single command
    license: MIT
    test: |
      system "#{bin}/my --version"
    install: |
      bin.install "my"
    dependencies:
      - name: rust
        type: build
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

# GitHub release configuration
release:
  github:
    owner: oleiade
    name: mymy
  draft: true
  prerelease: auto
  mode: replace
  header: |
    # mymy {{ .Tag }} Release

    Access the most common information about your system using a single command
  footer: |
    ## Installation

    * Binary downloads are available on the [releases page](https://github.com/oleiade/mymy/releases).
    * Packages for various platforms are also available.

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch